# Data Analysis

### Setup

First we import the necessary libraries:

In [45]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

Now we turn the crashes.csv files into a dataframe:

In [46]:
crashes_raw = pd.read_csv('data/crashes.csv')
crashes_raw.sample(10)

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT
56627,IT1:41_983(1.0),A,39010,ROADACC,9,2024,308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72529,IT1:41_983(1.0),A,62026,ROADACC,9,2020,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65600,IT1:41_983(1.0),A,56028,KILLINJ,F,2022,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23477,IT1:41_983(1.0),A,14038,KILLINJ,M,2020,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38469,IT1:41_983(1.0),A,21046,KILLINJ,F,2020,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32802,IT1:41_983(1.0),A,18017,KILLINJ,F,2023,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59623,IT1:41_983(1.0),A,44017,ROADACC,9,2023,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22013,IT1:41_983(1.0),A,13137,KILLINJ,M,2020,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91767,IT1:41_983(1.0),A,79018,KILLINJ,M,2024,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31558,IT1:41_983(1.0),A,17136,KILLINJ,M,2022,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Then we transform also the SITUAS .csv files into a dataframe:

In [47]:
cities_raw = pd.DataFrame()

for i in range(5):
    df_tmp = pd.read_csv('data/situas_202'+str(i)+'.csv',sep=';')
    cities_raw = pd.concat([cities_raw,df_tmp])
    print('situas_202'+str(i)+'.csv concatenated')

cities_raw.index = pd.RangeIndex(len(cities_raw))

situas_2020.csv concatenated
situas_2021.csv concatenated
situas_2022.csv concatenated
situas_2023.csv concatenated
situas_2024.csv concatenated

In [48]:
cities_raw.sample(10)

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
6223,4,18,78,78,78023,78023,Campana,NaN,CS,0,0,1962,2011,"104,6457",2020,1546,2020
5920,4,16,72,272,72043,72043,Terlizzi,NaN,BA,0,0,26986,2011,"69,2294",2020,26245,2020
17328,1,3,13,13,13065,13065,Cernobbio,NaN,CO,0,0,6402,2021,"12,2813",2022,6383,2022
11580,2,8,33,33,33021,33021,Fiorenzuola d'Arda,NaN,PC,0,0,14858,2021,"59,7690",2021,14858,2021
35492,2,8,37,237,37060,37060,Zola Predosa,NaN,BO,0,0,19117,2021,"37,7471",2024,19466,2024
29922,4,18,78,78,78017,78017,Bisignano,NaN,CS,0,0,9614,2021,"86,2241",2023,9480,2023
37542,4,16,73,73,73017,73017,Montemesola,NaN,TA,0,0,3608,2021,"16,4329",2024,3478,2024
2485,1,3,19,19,19016,19016,Casalbuttano ed Uniti,NaN,CR,0,0,4103,2011,"22,8750",2020,3692,2020
29523,4,14,70,70,70080,70080,Toro,NaN,CB,0,0,1243,2021,"24,0581",2023,1221,2023
28191,3,10,55,55,55014,55014,Giove,NaN,TR,0,0,1846,2021,"15,0881",2023,1830,2023

### Data cleaning

For safety reasons, we will implement data cleaning on copies of the original dataframes.

In [49]:
crashes = crashes_raw.copy()
cities = cities_raw.copy()

We start from the crashes dataframe:

In [50]:
crashes.info()

<class 'pandas.DataFrame'>
RangeIndex: 113856 entries, 0 to 113855
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DATAFLOW          113856 non-null  str
 1   FREQ              113856 non-null  str
 2   REF_AREA          113856 non-null  int64
 3   DATA_TYPE         113856 non-null  str
 4   RESULT            113856 non-null  str
 5   TIME_PERIOD       113856 non-null  int64
 6   OBS_VALUE         113856 non-null  int64
 7   OBS_STATUS        0 non-null       float64
 8   NOTE_DS           0 non-null       float64
 9   NOTE_REF_AREA     0 non-null       float64
 10  NOTE_DATA_TYPE    0 non-null       float64
 11  NOTE_RESULT       0 non-null       float64
 12  NOTE_TIME_PERIOD  0 non-null       float64
 13  BASE_PER          0 non-null       float64
 14  UNIT_MEAS         0 non-null       float64
 15  UNIT_MULT         0 non-null       float64
dtypes: float64(9), int64(3), str(4)
memory usage: 13.9 MB

we see that all columns from 7 to 15 are completely nan. We can therefore drop them without losing any information.

In [51]:
crashes = crashes.dropna(axis=1,how='all')
crashes.head()

          DATAFLOW FREQ  REF_AREA DATA_TYPE RESULT  TIME_PERIOD  OBS_VALUE
0  IT1:41_983(1.0)    A      1001   KILLINJ      F         2020          4
1  IT1:41_983(1.0)    A      1001   KILLINJ      F         2021          2
2  IT1:41_983(1.0)    A      1001   KILLINJ      F         2022          5
3  IT1:41_983(1.0)    A      1001   KILLINJ      F         2023          6
4  IT1:41_983(1.0)    A      1001   KILLINJ      F         2024          5

We can also drop the columns "DATAFLOW" and "FREQ". The first one indicates the dataset, while the second one simply states that data has been collected yearly. Both this columns are made of identical entries for every row.

In [52]:
crashes['DATAFLOW'].unique()

<StringArray>
['IT1:41_983(1.0)']
Length: 1, dtype: str

In [53]:
crashes['FREQ'].unique()

<StringArray>
['A']
Length: 1, dtype: str

In [54]:
crashes.drop(columns=['DATAFLOW','FREQ'],inplace=True)
crashes.head()

   REF_AREA DATA_TYPE RESULT  TIME_PERIOD  OBS_VALUE
0      1001   KILLINJ      F         2020          4
1      1001   KILLINJ      F         2021          2
2      1001   KILLINJ      F         2022          5
3      1001   KILLINJ      F         2023          6
4      1001   KILLINJ      F         2024          5

Now if we inspect the entries corrisponding to a given REF_AREA (i.e. a city) and year:

In [55]:
crashes[(crashes['REF_AREA']==1001) & (crashes['TIME_PERIOD']==2020)]

    REF_AREA DATA_TYPE RESULT  TIME_PERIOD  OBS_VALUE
0       1001   KILLINJ      F         2020          4
5       1001   KILLINJ      M         2020          0
10      1001   ROADACC      9         2020          4

We see that for each city and year there are 3 entries, labeled by DATA_TYPE and RESULT. In particular, DATA_TYPE discriminates between the crashes count (ROADACC) or the number of killed/injured (KILLINJ). To further distinguish between these last two categories, we make use of the column RESULT, labeling the number of killed (M) or injured (F) - while it is 9 for ROADACC since it doesn't carry any meaning. Thus, the OBS_VALUE entry can indicate at the same time the number of crashes, of victims or injured people.

This method might be more comfortable in data aquisition, but not in data visualization, so we shall reduce all this information into one single row for each couple (city,year). We start by merging DATA_TYPE and RESULT into a single column. This can be done by simply modifying the DATA_TYPE column accordingly:

In [56]:
crashes.loc[crashes['RESULT']=='M','DATA_TYPE'] = 'KILLED'
crashes.loc[crashes['RESULT']=='F','DATA_TYPE'] = 'INJURED'
crashes[(crashes['REF_AREA']==1001) & (crashes['TIME_PERIOD']==2020)]

    REF_AREA DATA_TYPE RESULT  TIME_PERIOD  OBS_VALUE
0       1001   INJURED      F         2020          4
5       1001    KILLED      M         2020          0
10      1001   ROADACC      9         2020          4

Now all information is encoded in DATA_TYPE, so we can drop the RESULT column and pivot our table.

In [57]:
crashes.drop(columns='RESULT',inplace=True)

In [58]:
crashes = crashes.pivot(index=['REF_AREA','TIME_PERIOD'],columns='DATA_TYPE',values='OBS_VALUE')
crashes.head(10)

DATA_TYPE             INJURED  KILLED  ROADACC
REF_AREA TIME_PERIOD
1001     2020               4       0        4
         2021               2       0        2
         2022               5       0        3
         2023               6       1        3
         2024               5       0        2
1002     2020              14       0        8
         2021               9       0        6
         2022               5       0        4
         2023              10       1        7
         2024               9       0        5

Now we just have to make this table a little nicer with respect to the columns' names.

In [59]:
crashes.columns.name = None
crashes.reset_index(inplace=True)
crashes.rename(columns={'TIME_PERIOD':'YEAR',
                        'REF_AREA':'CITY_CODE'},inplace=True)
crashes.head(10)

   CITY_CODE  YEAR  INJURED  KILLED  ROADACC
0       1001  2020        4       0        4
1       1001  2021        2       0        2
2       1001  2022        5       0        3
3       1001  2023        6       1        3
4       1001  2024        5       0        2
5       1002  2020       14       0        8
6       1002  2021        9       0        6
7       1002  2022        5       0        4
8       1002  2023       10       1        7
9       1002  2024        9       0        5

We can now be (momentarily) satisfied with crashes. Inspecting the cities dataframe:

In [60]:
cities.info()

<class 'pandas.DataFrame'>
RangeIndex: 39507 entries, 0 to 39506
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  39507 non-null  int64
 1   Codice Regione                  39507 non-null  int64
 2   Codice Provincia (Storico)      39507 non-null  int64
 3   Codice Provincia/Uts            39507 non-null  int64
 4   Codice Comune (alfanumerico)    39507 non-null  int64
 5   Codice Comune (numerico)        39507 non-null  int64
 6   Comune                          39502 non-null  str
 7   Comune (dizione straniera)      620 non-null    str
 8   Sigla automobilistica           39047 non-null  str
 9   Capoluogo di Provincia/Uts      39507 non-null  int64
 10  Capoluogo di Regione            39507 non-null  int64
 11  Popolazione legale              39507 non-null  int64
 12  Anno Censimento                 39507 non-null  int64
 13  Superficie (Kmq)                39507 non-null  str
 14  Anno (Superficie)               39507 non-null  int64
 15  Popolazione residente           39507 non-null  int64
 16  Anno (Popolazione residente)    39507 non-null  int64
dtypes: int64(13), str(4)
memory usage: 5.1 MB

Note that there are 5 nan entries in section "Comune". We ignore nans in "Comune (dizione straniera)" because they simply label cities that have only Italian name - in fact most of that column is made of nans.

In [61]:
cities[cities['Comune'].isna()]

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
164,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7998,2011,"24,6422",2020,7849,2020
8067,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7830,2021,"24,6422",2021,7830,2021
15971,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7830,2021,"24,6422",2022,7790,2022
23875,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7830,2021,"24,6422",2023,7688,2023
31775,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7830,2021,"24,6422",2024,7662,2024

Observing these entries we can see that there is one for each year. It is likely to be data referring to the same city, the name of which has been lost somehow. Inspecting the crashes dataframe by means of the city code leads us to the same conclusion:

In [62]:
crashes.loc[crashes['CITY_CODE']==1168]

     CITY_CODE  YEAR  INJURED  KILLED  ROADACC
776       1168  2020       11       0        8
777       1168  2021       11       0        9
778       1168  2022       10       0        7
779       1168  2023        9       0        7
780       1168  2024        7       0        5

By searching directly in the database, we find out that this code corresponds to the town of None (TO), in Piemonte. This is coherent with all other entries in the dataset corresponding to the same code. It might be possible that, while reading the .csv, None has been interpreted by Python as NaN! However, we can easily fix this issue.

In [63]:
cities.loc[cities['Codice Comune (numerico)']==1168,'Comune'] = 'None'
cities.info()

<class 'pandas.DataFrame'>
RangeIndex: 39507 entries, 0 to 39506
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  39507 non-null  int64
 1   Codice Regione                  39507 non-null  int64
 2   Codice Provincia (Storico)      39507 non-null  int64
 3   Codice Provincia/Uts            39507 non-null  int64
 4   Codice Comune (alfanumerico)    39507 non-null  int64
 5   Codice Comune (numerico)        39507 non-null  int64
 6   Comune                          39507 non-null  str
 7   Comune (dizione straniera)      620 non-null    str
 8   Sigla automobilistica           39047 non-null  str
 9   Capoluogo di Provincia/Uts      39507 non-null  int64
 10  Capoluogo di Regione            39507 non-null  int64
 11  Popolazione legale              39507 non-null  int64
 12  Anno Censimento                 39507 non-null  int64
 13  Superficie (Kmq)                39507 non-null  str
 14  Anno (Superficie)               39507 non-null  int64
 15  Popolazione residente           39507 non-null  int64
 16  Anno (Popolazione residente)    39507 non-null  int64
dtypes: int64(13), str(4)
memory usage: 5.1 MB