# Data Analysis

### Setup

First we import the necessary libraries:

In [34]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

Now we turn the crashes.csv files into a dataframe:

In [47]:
crashes = pd.read_csv('data/crashes.csv')
crashes.sample(10)

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT
48625,IT1:41_983(1.0),A,28044,KILLINJ,M,2022,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48956,IT1:41_983(1.0),A,28067,KILLINJ,M,2023,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68465,IT1:41_983(1.0),A,58094,ROADACC,9,2021,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35236,IT1:41_983(1.0),A,19002,KILLINJ,M,2022,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99368,IT1:41_983(1.0),A,88008,KILLINJ,M,2023,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66096,IT1:41_983(1.0),A,57002,ROADACC,9,2022,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47185,IT1:41_983(1.0),A,26085,KILLINJ,F,2024,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21324,IT1:41_983(1.0),A,13053,KILLINJ,F,2023,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23563,IT1:41_983(1.0),A,14045,KILLINJ,M,2022,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24383,IT1:41_983(1.0),A,15044,KILLINJ,M,2023,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Then we transform also the SITUAS .csv files into a dataframe:

In [35]:
cities = pd.DataFrame()

for i in range(5):
    df_tmp = pd.read_csv('data/situas_202'+str(i)+'.csv',sep=';')
    cities = pd.concat([cities,df_tmp])
    print('situas_202'+str(i)+'.csv concatenated')

cities.index = pd.RangeIndex(len(cities))

situas_2020.csv concatenated
situas_2021.csv concatenated
situas_2022.csv concatenated
situas_2023.csv concatenated
situas_2024.csv concatenated

In [49]:
cities.sample(10)

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
39027,1,3,97,97,97063,97063,Pagnona,NaN,LC,0,0,328,2021,"9,1968",2024,310,2024
16924,1,7,8,8,8011,8011,Camporosso,NaN,IM,0,0,5577,2021,"17,9485",2022,5608,2022
14851,5,20,90,90,90032,90032,Ittireddu,NaN,SS,0,0,481,2021,"23,6868",2021,481,2021
34471,2,4,22,22,22162,22162,Ruffrè-Mendola,NaN,TN,0,0,427,2021,"6,5801",2024,406,2024
8107,1,1,1,201,1209,1209,Quassolo,NaN,TO,0,0,339,2021,"3,9560",2021,339,2021
17171,1,3,12,12,12024,12024,Brusimpiano,NaN,VA,0,0,1170,2021,"5,9058",2022,1178,2022
12181,3,9,50,50,50003,50003,Calci,NaN,PI,0,0,6293,2021,"25,1051",2021,6293,2021
35693,3,11,43,43,43035,43035,Penna San Giovanni,NaN,MC,0,0,971,2021,"28,0835",2024,915,2024
3928,2,8,39,39,39016,39016,Russi,NaN,RA,0,0,12083,2011,"46,2594",2020,12136,2020
6784,5,19,84,84,84043,84043,Villafranca Sicula,NaN,AG,0,0,1426,2011,"17,6292",2020,1358,2020

### Data cleaning

We start from the crashes dataframe:

In [50]:
crashes.info()

<class 'pandas.DataFrame'>
RangeIndex: 113856 entries, 0 to 113855
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DATAFLOW          113856 non-null  str
 1   FREQ              113856 non-null  str
 2   REF_AREA          113856 non-null  int64
 3   DATA_TYPE         113856 non-null  str
 4   RESULT            113856 non-null  str
 5   TIME_PERIOD       113856 non-null  int64
 6   OBS_VALUE         113856 non-null  int64
 7   OBS_STATUS        0 non-null       float64
 8   NOTE_DS           0 non-null       float64
 9   NOTE_REF_AREA     0 non-null       float64
 10  NOTE_DATA_TYPE    0 non-null       float64
 11  NOTE_RESULT       0 non-null       float64
 12  NOTE_TIME_PERIOD  0 non-null       float64
 13  BASE_PER          0 non-null       float64
 14  UNIT_MEAS         0 non-null       float64
 15  UNIT_MULT         0 non-null       float64
dtypes: float64(9), int64(3), str(4)
memory usage: 13.9 MB

we see that all columns from 7 to 15 are completely nan. We can therefore drop them without losing any information.

In [51]:
crashes = crashes.dropna(axis=1,how='all')
crashes.head()

          DATAFLOW FREQ  REF_AREA DATA_TYPE RESULT  TIME_PERIOD  OBS_VALUE
0  IT1:41_983(1.0)    A      1001   KILLINJ      F         2020          4
1  IT1:41_983(1.0)    A      1001   KILLINJ      F         2021          2
2  IT1:41_983(1.0)    A      1001   KILLINJ      F         2022          5
3  IT1:41_983(1.0)    A      1001   KILLINJ      F         2023          6
4  IT1:41_983(1.0)    A      1001   KILLINJ      F         2024          5

We can also drop the columns "DATAFLOW" and "FREQ". The first one indicates the dataset, while the second one simply states that data has been collected yearly. Both this columns are made of identical entries for every row.

In [67]:
crashes['DATAFLOW'].unique()

<StringArray>
['IT1:41_983(1.0)']
Length: 1, dtype: str

In [68]:
crashes['FREQ'].unique()

<StringArray>
['A']
Length: 1, dtype: str

In [69]:
crashes.drop(columns=['DATAFLOW','FREQ'],inplace=True)
crashes.head()

   REF_AREA DATA_TYPE RESULT  TIME_PERIOD  OBS_VALUE
0      1001   KILLINJ      F         2020          4
1      1001   KILLINJ      F         2021          2
2      1001   KILLINJ      F         2022          5
3      1001   KILLINJ      F         2023          6
4      1001   KILLINJ      F         2024          5

Now if we inspect the entries corrisponding to a given REF_AREA (i.e. a city) and year:

In [70]:
crashes[(crashes['REF_AREA']==1001) & (crashes['TIME_PERIOD']==2020)]

    REF_AREA DATA_TYPE RESULT  TIME_PERIOD  OBS_VALUE
0       1001   KILLINJ      F         2020          4
5       1001   KILLINJ      M         2020          0
10      1001   ROADACC      9         2020          4

We see that for each city and year there are 3 entries, labeled by DATA_TYPE and RESULT. In particular, DATA_TYPE discriminates between the crashes count (ROADACC) or the number of killed/injuried (KILLINJ). To further distinguish between these last two categories, we make use of the column RESULT, labeling the number of killed (M) or injuried (F) - while it is 9 for ROADACC since it doesn't carry any meaning. Thus, the OBS_VALUE entry can indicate at the same time the number of crashes, of victims or injuried people.

This method might be more comfortable in data aquisition, but not in data visualization, so we shall reduce all this information into one single row for each couple (city,year).

Inspecting the cities dataframe:

In [37]:
cities.info()

<class 'pandas.DataFrame'>
RangeIndex: 39507 entries, 0 to 39506
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  39507 non-null  int64
 1   Codice Regione                  39507 non-null  int64
 2   Codice Provincia (Storico)      39507 non-null  int64
 3   Codice Provincia/Uts            39507 non-null  int64
 4   Codice Comune (alfanumerico)    39507 non-null  int64
 5   Codice Comune (numerico)        39507 non-null  int64
 6   Comune                          39502 non-null  str
 7   Comune (dizione straniera)      620 non-null    str
 8   Sigla automobilistica           39047 non-null  str
 9   Capoluogo di Provincia/Uts      39507 non-null  int64
 10  Capoluogo di Regione            39507 non-null  int64
 11  Popolazione legale              39507 non-null  int64
 12  Anno Censimento                 39507 non-null  int64
 13  Superficie (Kmq)                39507 non-null  str
 14  Anno (Superficie)               39507 non-null  int64
 15  Popolazione residente           39507 non-null  int64
 16  Anno (Popolazione residente)    39507 non-null  int64
dtypes: int64(13), str(4)
memory usage: 5.1 MB

Note that there are 5 nan entries in section "Comune". We ignore nans in "Comune (dizione straniera)" because they simply label cities that have only Italian name - in fact most of that column is made of nans.

In [42]:
cities[cities['Comune'].isna()]

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
164,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7998,2011,"24,6422",2020,7849,2020
8067,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7830,2021,"24,6422",2021,7830,2021
15971,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7830,2021,"24,6422",2022,7790,2022
23875,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7830,2021,"24,6422",2023,7688,2023
31775,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7830,2021,"24,6422",2024,7662,2024

Observing these entries we can see that there is one for each year. It is likely to be data referring to the same city, the name of which has been lost somehow. Since we cannot recover it in any trustworthy way, we will eliminate them from the dataset.

In [43]:
cities = cities[~cities['Comune'].isna()]
cities.info()

<class 'pandas.DataFrame'>
Index: 39502 entries, 0 to 39506
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  39502 non-null  int64
 1   Codice Regione                  39502 non-null  int64
 2   Codice Provincia (Storico)      39502 non-null  int64
 3   Codice Provincia/Uts            39502 non-null  int64
 4   Codice Comune (alfanumerico)    39502 non-null  int64
 5   Codice Comune (numerico)        39502 non-null  int64
 6   Comune                          39502 non-null  str
 7   Comune (dizione straniera)      620 non-null    str
 8   Sigla automobilistica           39042 non-null  str
 9   Capoluogo di Provincia/Uts      39502 non-null  int64
 10  Capoluogo di Regione            39502 non-null  int64
 11  Popolazione legale              39502 non-null  int64
 12  Anno Censimento                 39502 non-null  int64
 13  Superficie (Kmq)                39502 non-null  str
 14  Anno (Superficie)               39502 non-null  int64
 15  Popolazione residente           39502 non-null  int64
 16  Anno (Popolazione residente)    39502 non-null  int64
dtypes: int64(13), str(4)
memory usage: 5.4 MB