# Data Analysis

### Setup

First we import the necessary libraries:

In [34]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

Then we transform the SITUAS .csv files into a dataframe:

In [35]:
cities = pd.DataFrame()

for i in range(5):
    df_tmp = pd.read_csv('data/situas_202'+str(i)+'.csv',sep=';')
    cities = pd.concat([cities,df_tmp])
    print('situas_202'+str(i)+'.csv concatenated')

cities.index = pd.RangeIndex(len(cities))

situas_2020.csv concatenated
situas_2021.csv concatenated
situas_2022.csv concatenated
situas_2023.csv concatenated
situas_2024.csv concatenated

In [36]:
cities.head()

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
0,1,1,1,201,1001,1001,Agliè,NaN,TO,0,0,2644,2011,"13,1462",2020,2545,2020
1,1,1,1,201,1002,1002,Airasca,NaN,TO,0,0,3819,2011,"15,7393",2020,3633,2020
2,1,1,1,201,1003,1003,Ala di Stura,NaN,TO,0,0,462,2011,"46,3315",2020,459,2020
3,1,1,1,201,1004,1004,Albiano d'Ivrea,NaN,TO,0,0,1791,2011,"11,7314",2020,1638,2020
4,1,1,1,201,1006,1006,Almese,NaN,TO,0,0,6303,2011,"17,8756",2020,6355,2020

### Data cleaning

Inspecting the cities dataframe:

In [37]:
cities.info()

<class 'pandas.DataFrame'>
RangeIndex: 39507 entries, 0 to 39506
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  39507 non-null  int64
 1   Codice Regione                  39507 non-null  int64
 2   Codice Provincia (Storico)      39507 non-null  int64
 3   Codice Provincia/Uts            39507 non-null  int64
 4   Codice Comune (alfanumerico)    39507 non-null  int64
 5   Codice Comune (numerico)        39507 non-null  int64
 6   Comune                          39502 non-null  str
 7   Comune (dizione straniera)      620 non-null    str
 8   Sigla automobilistica           39047 non-null  str
 9   Capoluogo di Provincia/Uts      39507 non-null  int64
 10  Capoluogo di Regione            39507 non-null  int64
 11  Popolazione legale              39507 non-null  int64
 12  Anno Censimento                 39507 non-null  int64
 13  Superficie (Kmq)                39507 non-null  str
 14  Anno (Superficie)               39507 non-null  int64
 15  Popolazione residente           39507 non-null  int64
 16  Anno (Popolazione residente)    39507 non-null  int64
dtypes: int64(13), str(4)
memory usage: 5.1 MB

Note that there are 5 nan entries in section "Comune". We ignore nans in "Comune (dizione straniera)" because they simply label cities that have only Italian name - in fact most of that column is made of nans.

In [42]:
cities[cities['Comune'].isna()]

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
164,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7998,2011,"24,6422",2020,7849,2020
8067,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7830,2021,"24,6422",2021,7830,2021
15971,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7830,2021,"24,6422",2022,7790,2022
23875,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7830,2021,"24,6422",2023,7688,2023
31775,1,1,1,201,1168,1168,NaN,NaN,TO,0,0,7830,2021,"24,6422",2024,7662,2024

Observing these entries we can see that there is one for each year. It is likely to be data referring to the same city, the name of which has been lost somehow. Since we cannot recover it in any trustworthy way, we will eliminate them from the dataset.

In [43]:
cities = cities[~cities['Comune'].isna()]
cities.info()

<class 'pandas.DataFrame'>
Index: 39502 entries, 0 to 39506
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  39502 non-null  int64
 1   Codice Regione                  39502 non-null  int64
 2   Codice Provincia (Storico)      39502 non-null  int64
 3   Codice Provincia/Uts            39502 non-null  int64
 4   Codice Comune (alfanumerico)    39502 non-null  int64
 5   Codice Comune (numerico)        39502 non-null  int64
 6   Comune                          39502 non-null  str
 7   Comune (dizione straniera)      620 non-null    str
 8   Sigla automobilistica           39042 non-null  str
 9   Capoluogo di Provincia/Uts      39502 non-null  int64
 10  Capoluogo di Regione            39502 non-null  int64
 11  Popolazione legale              39502 non-null  int64
 12  Anno Censimento                 39502 non-null  int64
 13  Superficie (Kmq)                39502 non-null  str
 14  Anno (Superficie)               39502 non-null  int64
 15  Popolazione residente           39502 non-null  int64
 16  Anno (Popolazione residente)    39502 non-null  int64
dtypes: int64(13), str(4)
memory usage: 5.4 MB